---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: blocky
      version: 9.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.15

    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 4

    env:
      TZ: "Europe/Oslo"

    config: |
      httpPort: 4000
      logLevel: info

      upstream:
        externalResolvers:
        - 1.1.1.1

     # conditional:
     #   mapping:
     #     # CoreDNS IP
     #     casalani.de: tcp+udp:${LB_COREDNS}
     #     int.casalani.de: tcp+udp:${LB_COREDNS}

      blocking:
        blackLists:
          ads:
          - https://dbl.oisd.nl
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads

      prometheus:
        enable: true
        path: /metrics

    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LB_BLOCKY}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LB_BLOCKY}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    prometheus:
      serviceMonitor:
        enabled: true

    resources:
      requests:
        memory: 275Mi
        cpu: "0.01"
      limits:
        # memory: 2048Mi
        cpu: "0.05"

    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
