---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 9.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.16
    
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"

    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2
    
    env:
      TZ: "Europe/Oslo"
    
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LB_BLOCKY}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${LB_BLOCKY}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    config: |
      httpPort: 4000
      logLevel: info

      upstream:
        externalResolvers:
        - tcp-tls:${SECRET_NEXTDNS_ID}.dns1.nextdns.io:853
        - tcp-tls:${SECRET_NEXTDNS_ID}.dns2.nextdns.io:853

      conditional:
        mapping:
          ${SECRET_DOMAIN}: tcp+udp:${GATEWAY_IP}
      blocking:
        blackLists:
          ads:
          - https://dbl.oisd.nl
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads

      prometheus:
        enable: true
        path: /metrics

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - blocky
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
