# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Jqb/i8HD6NPWXTegOiI=,iv:gAWcRJ7a+ctvCAvHzAu0TemAzJA7n+uJlQQow3P2mw4=,tag:VjImvR1Cmz8CAfTEjYcjug==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GpyFQNpZM5Esy65plsPMfKVsVe3y,iv:5IwMlrkgE3CVT0B+c/cS7n54MBKAlTwVkO4s+cVUIJ8=,tag:cz2kurs42KUjokudDvkoCg==,type:str]
    SECRET_NEXTDNS_ID: ENC[AES256_GCM,data:5zIm2yG+,iv:1YaU5ZUfG4Gei026ELc5wWAE7rV3qvW6d2tMiM5bWlM=,tag:W7OXlLal6Rk7+1ZW8HHp5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-23T20:36:07Z"
    mac: ENC[AES256_GCM,data:x2M51jI0S5QSZmF//byPX1I+TwkA/vlcVRqN1PgAM6Amt5tmSlL4CyOJZphCOj+W9fu0i97fXN9KwXKCULVzoJqNCETKqajeKb6fu1ebM02RoL3nu1Jc7cPMMFSGDMskJwSbOGBBbuDqwtHyecrhBfEaaAR6gXNBNFzt+8qfYqc=,iv:xN5HbeWEBXaHH0l8Hs61mu1sWFyr2tJf4vyiyohPaPc=,tag:67c5EJe9jcnXgIUHpBTJOA==,type:str]
    pgp:
        - created_at: "2021-09-23T20:36:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA54uTaEdl0xAARAAhGuKj29TFRGXKC9tkgqWKIgw/wVAyZtmkNSXqx74jmYH
            pXWEC5IkPC+rmiAk3iDByFP33G+/bp1EHY9EVISUQbKJ0ub7HoMpQU2SrIvh4R8f
            EvmNgOeK0yU9TAOdlMLU/04YnTYonBHYz3QrWWqXo5yHr5y7WqBQMV8YmWTASTgT
            kJZZplhKeW0/bEgdSsGamviqZq2NWQIWKuWlyIPm4g+VAPHqkmb+0G79Z8t3MC0D
            9VPbnTjg+kdiK6XbOFXkNtrGJJa/Wq/fnlZ4GGGqf1rl1xHR5PIvXzJOfMIsdKUB
            vStf82AwKJWNYG6Bb7C4WqC6pLw4x0FB5bdEblIZxzA1kV1O1+9RQYmg2YpdE6EL
            O/lCiNZJElMtco+7p82u6XMYHd1fbVOSEWH57enuvg89ggId9HDidFJjaWXen15P
            GxyGXztEdweydtf6Xw6E3eGlQyT0Wl2wPv2cSBWsrzUTecAILsD5KBxrzvHI3ppa
            MkoS55y32t4/iGxDgV3RkBx7IaRu9uGkolCnFVFETLXCjySxO7RnkO++uFRqkZ6v
            +pGFEni5jpaQjdBu/QbPE5LSpL1lKwao/EJaI4ZZDjpROQ04msLOgPEzOl6REmdK
            PXryJ3vIeU879CfV4vvzTvoQV/6bWmJC0kU5RPnyE4DqevP5PnfQjs1d0gGw8UnS
            XgGEtAljihHexHpp9AxxbT1mfA0itvKrfyy6C9f10LsgmMtOhnn78328m7lIkAAv
            NoK6b26fJLI6owcw2c1MYz1SwvcWnxPTd9bZhU/q9h6ZUA9sKhwpup2SFSSeZI8=
            =0dFM
            -----END PGP MESSAGE-----
          fp: 5B590FD3ADB4D65E56401C9F9FD6C85F0534C51D
        - created_at: "2021-09-23T20:36:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4C26bmbwiwDAQ//bm+GvGoL3XDN59aUrSWGyN8esX00q4BsVwMnF0BRXM6k
            xs9gAIkGAFfqZnizyZprZvbx7vTVc6hH3tEYKk13wRRky/RNLcdoZYUTbPAI1vgt
            3Y+ebQoOGPGMGt5kZ30ILpTlq9TxEbzTyESdHvJgw23jsgtxCNybGqNHAFCmcmre
            QGr2VVD1cLEVErP+RkExD7PeOzCnfD5SFDQ24zgEXWGiv3Xr+tYFCbS5BlXlOqu3
            3W5pH11DxWA9AhCybr5Wyf75ZzFPqYjWvZZEByv3Kdocvi41U4poJDbXw4oN2Tsl
            kGI4lCItXxvb0oNKp8BNoh2LE1CdBOggVT3HlF3m/AfVtiDakSCxQ78xfpIYXy3J
            WRoer/6Z5Ho/e0ARONDVtrDg9uyELAhJG+H+O/DDn1KjtCp545wTe8a+emUGHn8z
            8HTsV9d4ucLAWXLmBwbtmxFCdCSIqlJj2oQktTX/fHtEILcF5XUBGR8HtCx2mK84
            Clo1fORSpWJeqJkRiDFPGsreao3B7mIMrkBKV8nCKrdhG0gvXGP36XBcp7BL92ch
            HnquZ4pYpMdXVv+nCi5clLXnB+IdKwzxx5C7JwPR9CLpB62H7v5dJQCO3NaDlZgc
            lkgYLO063lZNd6uXAB6x4zecmvmmjyZqxhNJfcTjsFTTtYKa0ZRnPmuqB3t0jU7S
            XgE8v2JbqAp+nc0BypGOb+JEDWiYDBIfdINfK8/4DVdutHNHYA0oskd8onLHFRNG
            Z+/JoPALbTPqTZ5WOKxLuzVyJ/ZsyJcwOVQ4JMm6oFFt6RUOizw0UNjucSthYG0=
            =zrs3
            -----END PGP MESSAGE-----
          fp: E68151A5EA31A3C6196943FC11F8E196E6ECD9C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
