---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.177.100-192.168.177.200
  SVC_TRAEFIK_ADDR: 192.168.177.100
  LB_BLOCKY: 
  GATEWAY_IP: 192.168.150.26
