---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.150.40-192.168.150.49
  SVC_TRAEFIK_ADDR: 192.168.150.40
  LB_BLOCKY: 192.168.150.41
  GATEWAY_IP: 192.168.150.2
