# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:D94N0RX/5vgR8dKIF665TsKgOROWI9E1+U12NbGZ5p/8ct8ZaZ9gOA==,iv:h5aidR2FhxsV3cDPu82bzLcQWFPlEApDgflTXeg8FP4=,tag:9M/H+ivuiqQqmL4/oRdQXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-23T20:41:38Z"
    mac: ENC[AES256_GCM,data:C5/hj/6VgtADYVUt95j3OIgr1tArp0QccON0+62ylcj+CVT+0L7aegAEnWCPoOW3H0nAquIA7JStdC+NwMRo+yOqniduTWb3gbLPQ2e4WxuAHN8Z+6tpNTIKgswpYy8KZ9BpelLb3o1vHLtybdGGmKghVwWzjhSjOsGuxxqKLzc=,iv:x+m62OE++GbG6NbvFsProWQgJie0/a7S9mham2nJCAE=,tag:/Xf/lvYGadvj+5dgfIJXrQ==,type:str]
    pgp:
        - created_at: "2021-09-23T20:41:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA54uTaEdl0xAARAAp1JFSKZ6N/rr/ri2FN4q6JasRyk5r/pn8aqXb8zUebTS
            y9nd3U5TvrclEAhzBO+HdQUeQksa5NpQr0nZSiIsZwObhN8HH9d/xkcBB8fbF9Zd
            Tul7+T/lqwi8PqlZcrJCKpAwa0XyoqEaeZu030s0XBEYUGTuGNI1sPC+w1Wcravc
            /ot4jJ45VlaNP0JlNSc3BXrQvwMitET++sZOXYrGwPuNDQ8xaAXqMfTQrRpeXj0z
            WdT4NdUqZ2SoMubvOZkXJIkt3nx3FOSCUCth1EL8qOuy5Wu7vFx1caTXGf5oRKPS
            jmqBKyY5uGtV5qH34UOfeMCqizZylX5BWoyAAWsZu9GGddaHDpZ78JP/VV6/HMh2
            gsYf5/jgaSeJKufNt6+4O+l3iEQmYPGXYNc7M7dAcWUOJi00CXXAIKUsDnf33jti
            U5aiekdNq+wMEs+fArWI43rQfRz+2HwbPu7LlwbLwDHG/Bv+FYwTFEGsI55BI0y/
            SnPHvzpDbcOX2N5BhrNd+yWSSQJO7KZHQGGKEZcs5GFDs2D0L9mGhXzHiXlVxHe6
            TDf4hDzr1aB//X8pKW9YIa25tKpCDC3QbWA+UZgFzpujsTo+mPFlRisfaScZSxuY
            VKgdhK5Y0imkYpAx5Mo7Ko3iw3c0N0s8aiQ3mSqYwwVRSciYRTnKnWnUsJPzD0PS
            XgG14eAhQU3j2gWO28b9IvedeUaG8d6dqeJTP8fL2nZCej8eN7RzxXwucsfc5+8S
            KDhbhH53NsK7XNgmJDFopCM4lGLVDvTY7pnIjYxdQiLNkv7n5WndabQWEsAL4Zc=
            =f8KN
            -----END PGP MESSAGE-----
          fp: 5B590FD3ADB4D65E56401C9F9FD6C85F0534C51D
        - created_at: "2021-09-23T20:41:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4C26bmbwiwDAQ//XaptqpUwFwsG6nOeTPLaBlFixv2wfWHl3zJxj73oXVhp
            boZMQmy0Q81DmH4lrldE8XNIInAy+nECd5CuaBpB/O0GsxZOs+lNLrt3k6bQ5X22
            C6vKv+RGbt4QUsL+VPtSxg6aJcR0A3YTJLD5i322vg9c+zCaemB7Am2feBMJ2nO/
            j/wMKHvHNsTriuVY2qZj5r1124xoGv8KB/Q+noBJTDL4/+UG7GrjIbdE0Qhn8chw
            sDg9sF54HS+f+BQWnvIWJJwgVkY7aoYWHTPdzJkBlWwqRLst8N4u+YoBTZTO7H/O
            0F3/5SQ+wAd++ifKWRE2fvcPZxTMM5uWyfp25pQnhu1bhE4yYXdwZRLSec4+s9gV
            7bmNxU8i1UoGlL0jadSb6sg80jpr/boQjS7v2e3+ckpST7eHX8WJkFnwbH7rtQFz
            4KbrOOAW5GQfJBCQ3w5olv58ll2du9hoib49n+Oj6mHSk2upVt9R7hVGUc6FVKpW
            ryskzcLPfllu9mANtNc3HM8/EJroZzvjRVtevirrCPf9I1HG0U0DxaWtSyZkI7IK
            uoxprakKlyw8P/IrdL8OaaBNSDGHplrpXD0jIt/lwE29Wm7OsG+VHDH/px5k2O4J
            OxZxp29ywaj4ak0xGgSMWGHLZB/R1kVbs/cZnsyGipE1Y0BwXr21+NLbxI4lmKnS
            XgHHaDz6qcHjcQeg4pvqbIOR2tBl+EtQCWAGNXA6LVds6tF2frX105ermeKu0vRI
            8mjUh8cPvov+tLMNiWQHR5wIjVOVZpY3L/WXwgmZouUP1Yyw09pPB7VMz7Jp8lc=
            =YDBD
            -----END PGP MESSAGE-----
          fp: E68151A5EA31A3C6196943FC11F8E196E6ECD9C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
