# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:VyrN0dWSGx4n6gtPMES9PSiVUf0xYTLsC8bpAvHgUXPfXPU0mg96og==,iv:0NK20xOZ9tNHB0sdbQU91LYrT9Ba9KR11IlDRTbeEoI=,tag:RsYnp2AaH1FAV5Nz1++AUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-18T16:58:39Z"
    mac: ENC[AES256_GCM,data:Ueteo4h9HHmpsJAoSDt7ELOIQu4IuYIS+OYwA0V5pqFqh3wfJHKnHHFOCeVNZdt0vUC1bLc0W82272QAhpXbWlFPvC8WfBWAIobIZ2hopnszsc87w0XXUsE8210RCpkyxP6P0/dCje+nMo2CgPyoGJM6cKyTK6kWhRPVXzXRRFI=,iv:ty52bP8bVQjICURJpXUAxQIIs0XDrngy8VeIrfQN+yA=,tag:ipRW3BfnuVakBQAnZs314g==,type:str]
    pgp:
        - created_at: "2021-09-18T16:58:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA54uTaEdl0xAAQ//WvEYzXm7Zjuqkbc/ofpbXyJQfTJWvDjVUbjJKr2d6trx
            1w4/EZgqbttLQaqKUe35kwiHHZ1DK0XTOriMOb4GEdiu+3joZ6jwSRqFsL/Fc7BI
            UL+ieaGsCbrvWfWWZZH4n6fodgLE3TOLVGwd0jzne9DFqmrTKn6R5B96kELlTIy+
            qWVlnoj+aIMs/pMvzwAocveRXdmABw4PMnoe42KLPP25FDDoNTP7HzBorfEriIll
            F1uSJ+xfnyrOF/mTqoo38usHb+O+1f6V8e8xiNh6Y/5nC0Pd4AyXHELcNNUZNFkU
            oRMaf902cpH3A0NGIk/WZaqPF+GB0PuXUQO+v3ucGWlf/51nv6BV+uwvsqSeoORq
            mmZ+oMK6ghcRK5vma/H4l01q2g/omeca0RVHNWlh1Qu12NEokEsTXJsks80QvkXE
            O/v/ywR2B2bvaY6iQBVddDDwQmdlU0vpT9cNXmBxCzQLQtRUYm33+w+BA2q/pE6X
            0fSsAED8jkrRF9ww9hwsZ6U4sXvSNs71oRXxwj9BcVB6oN4PdqIghqU3x2XNxwdA
            9GK4LMiMF28Jj2f9/1l+RQGu4rEfxl6PEIXcF98vauB4urzfNqUjcYMTg1TAYzua
            q2QzZdFjmOw/EHSogMPqsI7iMhPn9SJbt+qY0tKIHB63YMnApVVxBrmTq6wrXiHS
            XgGgnTk0LwtYzXlf1c/mU7PhgdHVcRB8OstpdHHSF77Rq8cxFxVM/AMCnP84Mmzm
            lMn1S5MM+m7RauGidcPC0vXitPx2bTmucOmq8b9fsl4dcZi3uboQ1LGjJdNfxhE=
            =uYRr
            -----END PGP MESSAGE-----
          fp: 5B590FD3ADB4D65E56401C9F9FD6C85F0534C51D
        - created_at: "2021-09-18T16:58:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4C26bmbwiwDAQ/8DqT5+Qr0w9OfKWcCOi38Bbo2exqMxnWY/4ipxlV8trBw
            T3XwgA0n4+iw+Fe3sovYBGTC1d+6AeQTgUwdyj7MzYjndtZuWLWyc7JiSnPU+o7k
            VzSiO+DJTYIUHSRvlHpVbGj2DVV9zVMYPF223pXXo5GdTxQ22V0P8HNXAOQHsxAd
            4zeV1Fnv13iXKElohrcW6S6NeMkgPF5lFKKOkTAoThS8Ttl1YCgRzIWNmQuhq33f
            w0i4sPFUwh43JXtkjWHUcANk60VqzHkM+hkdFW0bmscjy224Gp8sGZSwch+q6lQE
            APHpEDTkgnFb8yPSkUKC6SEXFnLHmWwqjwM8YciIz7vDjqbPHnpJavOdaRnWs6xH
            5XvoXEip4dTypXvI3UXhSwuG1DuXt2So35mP84OFORhtMuU+l5DPHwemJIBCJTXU
            S2xOYsaXzPhdN0WJjgaTaTFvl5FuBV7VBC6i3gNFDKh4z4DE8dyPHHnU458K9gwR
            JR0ZSmoi0TRMUKExo51kiq/IaCafYa+swQrAxfpUFoIZBo6Oq+1WO0kXJIrToTA4
            fuIcPcNHTcVPTtC8rcF9z8rlcEUr95yk6kkpsvhsoQv8n8PuU1uufkhQb2IPCIvj
            reLk7YwbEufrJ8nOj7xW3ycY3u6SkD7I7tpXy7RjyfuxQxwhKCANtKBeoEH7hcnS
            XgHA8PdPiztJJJePwM7OICK1QRJM6nJJOH6PQ0mUqukOPIS7Gm078KdNPy3fS84U
            JulYMaqJfnFbu/NoW+s3bNcGYMJy2q88DsGgXrOTvvhXo/Pdnz3VZaaW+kZns64=
            =J6l7
            -----END PGP MESSAGE-----
          fp: E68151A5EA31A3C6196943FC11F8E196E6ECD9C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
